export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_ALL_ITEMS = 'REMOVE_ALL_ITEMS';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const SHOW_MODAL = 'SHOW_MODAL';
export const EMPTY_BASKET = 'EMPTY_BASKET';
export const ADD_ORDER = 'ADD_ORDER';

export const EMAIL_PASSWORD_AUTH_SIGNIN = 'EMAIL_PASSWORD_AUTH_SIGNIN';
export const EMAIL_PASSWORD_AUTH_SIGNOUT = 'EMAIL_PASSWORD_AUTH_SIGNOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_USER = 'FETCH_USER';
export const USER_POST = 'USER_POST';
export const UPDATE_USER = 'UPDATE_USER';




